name = "the-deepak-kharol-project"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "todo-db"
database_id = "ee9756dd-343d-4806-9c63-4756fa263f9e"

[[r2_buckets]]
binding = "ATTACHMENTS"
bucket_name = "todo-attachments"
